FROM miktex/miktex

RUN mpm --install ae && \
    mpm --install amscls && \
    mpm --install amsmath && \
    mpm --install avantgar && \
    mpm --install babel && \
    mpm --install babel-english && \
    mpm --install babel-french && \
    mpm --install babel-german && \
    mpm --install babel-spanish && \
    mpm --install biblatex && \
    mpm --install bibtex && \
    mpm --install bibtex8bit && \
    mpm --install bibtex8bit-polish && \
    mpm --install bidi && \
    mpm --install bookman && \
    mpm --install booktabs && \
    mpm --install carlisle && \
    mpm --install cbcoptic && \
    mpm --install chktex && \
    mpm --install chngcntr && \
    mpm --install cm && \
    mpm --install colortbl && \
    mpm --install courier && \
    mpm --install cweb && \
    mpm --install cyrillic && \
    mpm --install dehyph && \
    mpm --install dehyph-exptl && \
    mpm --install dvipdfmx && \
    mpm --install dvips && \
    mpm --install ec && \
    mpm --install elhyphen && \
    mpm --install enctex && \
    mpm --install etex && \
    mpm --install etex-pkg && \
    mpm --install etoolbox && \
    mpm --install euenc && \
    mpm --install eurosym && \
    mpm --install fancyhdr && \
    mpm --install float && \
    mpm --install fontconfig && \
    mpm --install fontname && \
    mpm --install fontspec && \
    mpm --install framed && \
    mpm --install geometry && \
    mpm --install ghostscript && \
    mpm --install graphics && \
    mpm --install graphics-cfg && \
    mpm --install graphics-def && \
    mpm --install gsftopk && \
    mpm --install helvetic && \
    mpm --install hyperref && \
    mpm --install hyph-utf8 && \
    mpm --install ifxetex && \
    mpm --install jknappen && \
    mpm --install knuth-lib && \
    mpm --install knuth-local && \
    mpm --install koma-script && \
    mpm --install latex-fonts && \
    mpm --install lm && \
    mpm --install logreq && \
    mpm --install ltxbase && \
    mpm --install ltxmisc && \
    mpm --install lua-alt-getopt && \
    mpm --install luainputenc && \
    mpm --install lualibs && \
    mpm --install luamplib && \
    mpm --install luaotfload && \
    mpm --install luatexbase && \
    mpm --install luatextra && \
    mpm --install makeindex && \
    mpm --install metafont && \
    mpm --install metapost && \
    mpm --install mflogo && \
    mpm --install mflogo-font && \
    mpm --install mfware && \
    mpm --install minitoc && \
    mpm --install mptopdf && \
    mpm --install ms && \
    mpm --install multirow && \
    mpm --install ncntrsbk && \
    mpm --install oberdiek && \
    mpm --install palatino && \
    mpm --install pdftex && \
    mpm --install pgf && \
    mpm --install plain && \
    mpm --install polyglossia && \
    mpm --install poppler && \
    mpm --install pslatex && \
    mpm --install psnfss && \
    mpm --install pstricks && \
    mpm --install psutils && \
    mpm --install rsfs && \
    mpm --install ruhyphen && \
    mpm --install tex-ini-files && \
    mpm --install texinfo && \
    mpm --install thumbpdf && \
    mpm --install times && \
    mpm --install tools && \
    mpm --install ttf2pk && \
    mpm --install ukrhyph && \
    mpm --install unicode-data && \
    mpm --install upquote && \
    mpm --install url && \
    mpm --install utopia && \
    mpm --install xcolor && \
    mpm --install xetex && \
    mpm --install xgreek && \
    mpm --install xindy && \
    mpm --install xkeyval && \
    mpm --install xltxtra && \
    mpm --install xstring && \
    mpm --install xunicode && \
    mpm --install xypic && \
    mpm --install zapfchan && \
    mpm --install zapfding && \
    mpm --install zerohyph
